using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Library_dApp
{
    public partial class LendForm : DevExpress.XtraEditors.XtraForm
    {
        public LendForm()
        {
            InitializeComponent();
            borrowedhistoryBindingSource.DataSource = new Borrowedhistory();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Library_dApp.LibraryEntities dbContext = new Library_dApp.LibraryEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Users.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    UsernameTextEdit.Properties.DataSource = dbContext.Users.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void CancelButton_Click(object sender, EventArgs e)
        {
            DialogResult = DialogResult.OK;
            this.Close();
        }

        private void SaveButton_Click(object sender, EventArgs e)
        {
            var lendbook = (Borrowedhistory)borrowedhistoryBindingSource.DataSource;

            var db = new LibraryEntities();

            db.Borrowedhistories.Add(lendbook);
            db.SaveChanges();

            DialogResult = DialogResult.OK;
            XtraMessageBox.Show("book lent sucessfully");
        }
    }
}